export const CHARACTERS_START = 'CHARACTERS_START';
export const CHARACTERS_SUCCESS = 'CHARACTERS_SUCCESS';
export const CHARACTERS_FAILURE = 'CHARACTERS_FAILURE';
export const CHARACTERS_FAV = 'CHARACTERS_FAV';
