export const CHARACTERS_SEARCH_START = 'CHARACTERS_SEARCH_START';
export const CHARACTERS_SEARCH_SUCCESS = 'CHARACTERS_SEARCH_SUCCESS';
export const CHARACTERS_SEARCH_FAILURE = 'CHARACTERS_SEARCH_FAILURE';
export const CHARACTERS_SEARCH_EMPTY = 'CHARACTERS_SEARCH_EMPTY';
